import './globals.css'
import { DataContextProvider } from './store/dataContext'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <DataContextProvider>
          {children}
        </DataContextProvider>
        </body>
    </html>
  )
}
